---
functional:
  - Пользователь должен иметь возможность авторизоваться на сайте.
  - Пользователь должен иметь возможность создавать игру.
  - Пользователь должен иметь возможность подключиться к игре другого игрока.
  - Пользователь должен иметь возможность наблюдать за игрой двух других игроков.
  - Пользователь должен иметь возможность видеть задание игры.
  - Пользователь должен иметь возможность видеть окно редактора кода.
  - Пользователь должен иметь возможность изменить язык программирования.
  - Пользователь должен иметь возможность видеть код своего соперника в режиме онлайн.
  - Пользователь должен иметь возможность проверить свое решение кнопкой check.
  - Пользователь должен иметь возможность продолжить игру, если второй игрок вылетел.
  - Пользователь должен иметь возможность переподключиться к игре в случае вылета.
  - Пользователь должен иметь возможность завершить игру.
  - Пользователь должен иметь возможность видеть окно результат игры.
  - Пользователь должен иметь возможность выйти из игры в случае победы.
  - Пользователь должен иметь возможность выйти из игры в случае проигрыша.
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть удобным на мобильном устройстве.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
  - Сайт должен работать как SPA приложение, без перезагрузки страницы.
implicit:
  - Пользователь должен иметь возможность изменить язык отображения заданий.
